name: Ejercicio 1
on:
  push:
    branches:
      - main
jobs:
  ejericio1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
  
      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      - name: run lint
        run: npm run lint

      - name: Run tests
        run: npm test

 
  deploy:
    runs-on: ubuntu-latest
    needs: ejericio1
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Build the project
        run: npm run build

      - name: Deploy to serve
        run: |
          echo "Deploying to server..."
          